default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: paker87
  pool: 5

development:
  <<: *default
  host: localhost
  database: testapp_development
  pool: 50

test:
  <<: *default
  host: localhost
  database: testapp_test
  pool: 50

production:
  <<: *default
  database: testapp_production
  username: testapp
  password: <%= ENV['TESTAPP_DATABASE_PASSWORD'] %>
